[general]
framerate = 60
bars = 16
bar_width = 1
bar_spacing = 0
sensitivity = 180
overshoot = 100

[input]
method = alsa
source = plughw:Loopback,1,2
sample_rate = 48000
samples = 100

[output]
method = raw
data_format = binary
channels = mono
mono_option = average
raw_target = /tmp/cava_fifo_sa
bit_format = 8bit

[smoothing]
integral = 100
monstercat = 1
waves = 0
gravity = 80
noise_reduction = 0.80

[eq]
1 = 2
2 = 2
3 = 2
4 = 2
5 = 2
6 = 2
7 = 2
8 = 2