description: null
devices:
  adjust_period: null
  capture:
    channels: 2
    device: hw:CARD=Loopback,DEV=1
    format: null
    labels: null
    link_mute_control: null
    link_volume_control: null
    stop_on_inactive: null
    type: Alsa
  capture_samplerate: 96000
  chunksize: 4096
  enable_rate_adjust: null
  multithreaded: true
  playback:
    channels: 8
    device: audio_out
    format: null
    type: Alsa
  queuelimit: 2
  rate_measure_interval: null
  resampler: null
  samplerate: 44100
  silence_threshold: null
  silence_timeout: null
  stop_on_rate_change: null
  target_level: null
  volume_limit: null
  volume_ramp_time: null
  worker_threads: null
filters:
  Bass:
    description: Shows Bass
    parameters:
      freq: 60
      gain: 3
      q: 1
      type: Lowshelf
    type: Biquad
  Bass (Mid):
    description: Bass Mid
    parameters:
      freq: 80
      gain: 4
      q: 1
      type: Lowshelf
    type: Biquad
  Flanger:
    description: null
    parameters:
      delay_ms: 3
      depth_ms: 3
      phase_deg: 180
      regen: 50
      shape: triangle
      speed_hz: 1
      wet: 0.5
      width: 50
    type: Flanger
  Gain:
    description: ''
    parameters:
      gain: -10
      inverted: false
      mute: false
      scale: dB
    type: Gain
  Parametric Equalizer:
    description: Graphic equaliser
    parameters:
      freq_max: 20000
      freq_min: 45
      gains:
      - 7
      - 5.6
      - 0.3
      - -2.3
      - -3.4
      - -4.9
      - -5.6
      - -5.8
      - -6
      - -5.4
      - -4.5
      - -3.8
      - -1.7
      - 2.7
      - 4.7
      type: GraphicEqualizer
    type: BiquadCombo
  Pitch:
    description: null
    parameters:
      semitones: 0
      tempo: 1
      wet: 1
    type: Pitch
  Reverb:
    description: null
    parameters:
      hf_damping: 0
      pre_delay_ms: 0
      reverberance: 30
      room_scale: 10
      stereo_depth: 0
      wet: 0.13
      wet_gain_db: 25
    type: Reverb
  Treble:
    description: null
    parameters:
      freq: 19000
      gain: 1
      q: 0.9
      type: Peaking
    type: Biquad
mixers:
  Distributer:
    channels:
      in: 2
      out: 8
    description: null
    labels: null
    mapping:
    - dest: 0
      mute: false
      sources:
      - channel: 0
        gain: 0
        inverted: false
        mute: false
        scale: dB
    - dest: 1
      mute: false
      sources:
      - channel: 1
        gain: 0
        inverted: false
        mute: false
        scale: dB
    - dest: 2
      mute: false
      sources:
      - channel: 0
        gain: 0
        inverted: false
        mute: false
        scale: dB
    - dest: 3
      mute: false
      sources:
      - channel: 1
        gain: 0
        inverted: false
        mute: false
        scale: dB
    - dest: 4
      mute: false
      sources:
      - channel: 0
        gain: 0
        inverted: false
        mute: false
        scale: dB
    - dest: 5
      mute: false
      sources:
      - channel: 1
        gain: 0
        inverted: false
        mute: false
        scale: dB
    - dest: 6
      mute: false
      sources:
      - channel: 0
        gain: 0
        inverted: false
        mute: false
        scale: dB
    - dest: 7
      mute: false
      sources:
      - channel: 1
        gain: 0
        inverted: false
        mute: false
        scale: dB
  Unnamed Mixer 2:
    channels:
      in: 8
      out: 2
    description: null
    labels: null
    mapping:
    - dest: 0
      mute: false
      sources:
      - channel: 0
        gain: 0
        inverted: false
        mute: false
        scale: dB
      - channel: 2
        gain: 0
        inverted: false
        mute: false
        scale: dB
      - channel: 4
        gain: 0
        inverted: false
        mute: false
        scale: dB
      - channel: 6
        gain: 0
        inverted: false
        mute: false
        scale: dB
    - dest: 1
      mute: false
      sources:
      - channel: 1
        gain: 0
        inverted: false
        mute: false
        scale: dB
      - channel: 3
        gain: 0
        inverted: false
        mute: false
        scale: dB
      - channel: 5
        gain: 0
        inverted: false
        mute: false
        scale: dB
      - channel: 7
        gain: 0
        inverted: false
        mute: false
        scale: dB
pipeline:
- bypassed: true
  channels: null
  description: null
  names:
  - Gain
  type: Filter
- bypassed: true
  channels: null
  description: null
  names:
  - Pitch
  type: Filter
- bypassed: false
  channels: null
  description: null
  names:
  - Reverb
  type: Filter
- bypassed: false
  channels: null
  description: null
  names:
  - Bass
  - Bass (Mid)
  - Parametric Equalizer
  type: Filter
- bypassed: false
  description: null
  name: Distributer
  type: Mixer
processors:
  Unnamed Processor 1:
    description: null
    parameters:
      attack: 0.025
      channels: 2
      clip_limit: null
      factor: 5
      makeup_gain: 15
      monitor_channels:
      - 0
      - 1
      process_channels:
      - 0
      - 1
      release: 1
      soft_clip: false
      threshold: -25
    type: Compressor
title: Parametric EQ 10-Band
