description: null
devices:
  adjust_period: null
  capture:
    channels: 2
    device: hw:CARD=Loopback,DEV=1
    labels: null
    link_mute_control: null
    link_volume_control: null
    stop_on_inactive: null
    type: Alsa
  capture_samplerate: 44100
  chunksize: 4096
  enable_rate_adjust: null
  multithreaded: true
  playback:
    channels: 8
    device: audio_out
    format: null
    type: Alsa
  queuelimit: 2
  rate_measure_interval: null
  resampler:
    type: Synchronous
  samplerate: 96000
  silence_threshold: null
  silence_timeout: null
  stop_on_rate_change: null
  target_level: null
  volume_limit: null
  volume_ramp_time: null
  worker_threads: null
filters:
  15 Band EQ:
    description: null
    parameters:
      freq_max: 19000
      freq_min: 45
      gains:
      - 3
      - -2.3
      - -1.3
      - -2.6
      - -3.6
      - -4
      - -3.9
      - -4.3
      - -3.8
      - -3.2
      - -2.5
      - -1.8
      - -0.3
      - 3.2
      - 6.6
      type: GraphicEqualizer
    type: BiquadCombo
  Bass:
    description: null
    parameters:
      freq: 60
      gain: 7
      slope: 6
      type: Lowshelf
    type: Biquad
  Bass 80:
    description: null
    parameters:
      freq: 80
      gain: 10
      slope: 5
      type: Lowshelf
    type: Biquad
  Flanger:
    description: null
    parameters:
      delay_ms: 0
      depth_ms: 2
      phase_deg: 0
      regen: 10
      shape: sine
      speed_hz: 0.8
      wet: 0.5
      width: 90
    type: Flanger
  Gain:
    description: null
    parameters:
      gain: -10
      inverted: null
      mute: null
      scale: dB
    type: Gain
  Pitch:
    description: null
    parameters:
      semitones: 5
      tempo: 1
      wet: 1
    type: Pitch
  Reverb:
    description: null
    parameters:
      hf_damping: 50
      pre_delay_ms: 5
      reverberance: 40
      room_scale: 50
      stereo_depth: 50
      wet: 0.2
      wet_gain_db: 20
    type: Reverb
  Treble:
    description: null
    parameters:
      freq: 19000
      gain: 1
      q: 1.5
      type: Peaking
    type: Biquad
mixers:
  Main Distributer:
    channels:
      in: 2
      out: 8
    description: null
    labels:
    - DAC L
    - DAC R
    - ROOM L
    - ROOM R
    - CAVA L
    - CAVA R
    - BT L
    - BT R
    mapping:
    - dest: 0
      mute: false
      sources:
      - channel: 0
        gain: 0
        inverted: false
        mute: false
        scale: dB
    - dest: 1
      mute: false
      sources:
      - channel: 1
        gain: 0
        inverted: false
        mute: false
        scale: dB
    - dest: 2
      mute: false
      sources:
      - channel: 0
        gain: 0
        inverted: false
        mute: false
        scale: dB
    - dest: 3
      mute: false
      sources:
      - channel: 1
        gain: 0
        inverted: false
        mute: false
        scale: dB
    - dest: 4
      mute: false
      sources:
      - channel: 0
        gain: 0
        inverted: false
        mute: false
        scale: dB
    - dest: 5
      mute: false
      sources:
      - channel: 1
        gain: 0
        inverted: false
        mute: false
        scale: dB
    - dest: 6
      mute: false
      sources:
      - channel: 0
        gain: 0
        inverted: false
        mute: false
        scale: dB
    - dest: 7
      mute: false
      sources:
      - channel: 1
        gain: 0
        inverted: false
        mute: false
        scale: dB
pipeline:
- bypassed: false
  channels: null
  description: null
  names:
  - Gain
  type: Filter
- bypassed: true
  description: null
  name: spatial
  type: Processor
- bypassed: true
  channels: null
  description: null
  names:
  - Pitch
  type: Filter
- bypassed: true
  channels: null
  description: null
  names:
  - Flanger
  type: Filter
- bypassed: true
  channels: null
  description: null
  names:
  - Reverb
  type: Filter
- bypassed: null
  description: null
  name: Main Distributer
  type: Mixer
- bypassed: false
  channels:
  - 0
  - 1
  - 2
  - 3
  description: null
  names:
  - 15 Band EQ
  type: Filter
- bypassed: false
  channels:
  - 0
  - 1
  - 2
  - 3
  description: null
  names:
  - Bass
  - Bass 80
  - Treble
  type: Filter
processors:
  spatial:
    description: null
    parameters:
      channels: 2
      mid_gain_db: 1
      side_gain_db: 1
      width: 2
    type: MidSide
title: Parametric EQ 10-Band
